### PR TITLE
IP Reverse DNS

### PR DESCRIPTION
**Pull request by jammin84**
Fix for Issue #21 - Adds possibility for storing reverse IP records.

Note: there is also a minor node_plot fix i found when doing a diff of master and the WAFN version.

### CODE REVIEW

**Comment by spinza** [comment]
Just to clarify you will have nslookup www.node.wafn
Will give 172.18.20.10.
Nslookup 172.18.20.10 will give sometext.node.wafn.
What will nslookup sometext.node.wafn give?

**Comment by jammin84** [comment]
> nslookup www.node.wafn > 172.18.20.10 
> nslookup 172.18.20.10 > sometext.node.wafn.
> What will 
> nslookup sometext.node.wafn give?"
> - Spinza

if there _is_ a forward record then you'd expect sometext.node.wafn > 172.18.20.10
if there _isnt_ a forward record then you'll get nothing. This is pretty common.

Here is a common example from an MX.

```
dig MX gmail.com > gmail-smtp-in.l.google.com.
dig gmail-smtp-in.l.google.com > 64.233.187.27
dig -x  64.233.187.27 > tj-in-f27.1e100.net.
dig tj-in-f27.1e100.net > 64.233.187.27, 216.239.32.27
```

You can do a trace to google.com or something random .. then do a forward lookup on one of the resolved reverse's. majority wont have a forward

**Comment by jammin84** [comment]
essentially forwards are used commonly for services and are "memorable"
www.node.wafn
mail.node.wafn
etc.

Reverse's are used commonly for diagnosis. In these examples below the reverse give information about port identification, server reference, location, country, etc.
srv1.sydney.australia.node.wafn
port2.ny.usa.node.wafn

In saying all of that. Theres nothing to say that a forward and reverse just match.
mail.node.wafn > 10.10.10.10
10.10.10.10 > mail.node.wafn

**Comment by spinza** [comment]
Ah ok.  Can I suggest the following then in your PR:
forward, reverse and both.  With both being the default?
We use "both" :)

**Comment by spinza** [comment]
or "both" could be "forward & reverse" (more descriptive)

**Comment by jammin84** [comment]
for a "both" record how would you display it on the network tab?
- once in forward and once in reverse list?
- another list for both?

**Comment by jammin84** [comment]
perhaps just generating a forward and reverse record when a "both" is created would be best?

**Comment by spinza** [comment]
Yeah the last option was what I had in mind.  Can we rename it "forward & reverse" (or at least that's what we display).  

I haven't tested your PR yet.  You've been busy.  I've been busy fixing bugs after moving all our services and dns on our side.  And doing a few more moves.

**Comment by jammin84** [comment]
ok, so another list for "forward & reverse"

re: busy - Just trying to get the WAFN and Southern-Wind versions aligned. Make updating easier.

**Comment by spinza** [comment]
Do you have separate lists for forward and reverse? If so then yes a separate list top?  So that would be 3 lists forward & reverse, forward only, reverse only

**Comment by jammin84** [comment]
@spinza back to you :wink:

**Comment by spinza** [comment]
:+1:  I have a bit of a list to go through now. :smiley:

**Comment by spinza** [comment]
You need to update https://github.com/southern-wind/wind/blob/master/tools/update.php#L22
From 1.2 (if you apply my PR to fix 1.2) to 1.3

**Comment by spinza** [comment]
I fixed 1.2 retrospectively.  Should be fine as I don't think anyone installed it.  
See #39 

Also see issue #41 

How do you want to roll forward.  The db by default doesnt work because of the unsigned ints. 

I propose we fix the base sql pre 1.1 for now.  But future fixes should be done via schema updates.

**Comment by jammin84** [comment]
nice work on the above mentioned issues. They are now merged.

Re: DB updates.
While initially I agreed with the fix. Writing this, I'm thinking otherwise.

The install/schema will always be the "Current" full base (ie fresh install), with the tools/update only for those "upgrading".

This also aligns our own /README "There have been changes in the Database. .... For your convenience there is an updater script in /tools that can only run in cli."

So following that logic it needs to be included into the 1.2 update. 

This way if an existing WiND ($version <= v1.1-0-a1) user was converting to S-Wind .. the tools/update.php will work.

@spinza Please re-open #41 if you agree

**Comment by spinza** [comment]
Ok lets plan the schema fix first.  You would then need to update this patch also.  Depending on what is fixed where.

**Comment by jammin84** [comment]
waiting on #49

**Comment by jammin84** [comment]
I accidentally committed straight to master. This has since been undone.

```
# git reset --soft HEAD^
# git push origin +master
To https://github.com/southern-wind/wind.git
 + ac1a6c4...3c766cb master -> master (forced update)
```

Since doing the above back-peddle, I've rechecked schema.sql, etc and the "current version" is correctly showing 1.2

**Comment by spinza** [comment]
Ja I still operate off my own fork for PR.  Maybe safer to do that?

**Comment by spinza** [comment]
We could turn off commit via ssh on main?  I'm guessing it is an option?

**Comment by jammin84** [comment]
agreed.
in settings > branches .. can protect the master branch

**Comment by spinza** [comment]
Cool I've protected the master branch.

**Pull request merged**
