### PR TITLE
Remember previous tab while editing node.

### PR DESCRIPTION
**Pull request by MDE186**
Remember last working tab when editing a node.

i.e. entering an ip/subnet will remember 'network tab' and not take you back to 'node info'

issue #12

### CODE REVIEW

**Comment by spinza** [comment]
Can we make the PRs/commits a little more descriptive in future.  Not just yours but all of them. I'm wanting to dump a list of commits to people to say this is what's improved but the commits aren't very descripive

**Comment by spinza** [comment]
Tested this PR on wind-dev.  Seems to be working.  @jammin84  over to you.

**Comment by jammin84** [comment]
@MDE186 nice use of js localStorage.

Will test it out.

**Comment by jammin84** [comment]
Needs to be per node.
changing to another node will always take you back to the saved tab.

Also, can I suggest a time interval. So not changing tabs on that node in the last 30sec (for example) will then default back to the "info" tab next time the node edit view is loaded.

**Comment by jammin84** [comment]
fyi 30sec probably isn't sufficient. They may spend longer than that editing a page. I'm sure you'll come up with something.

**Comment by MDE186** [comment]
I will change localStorage to sessionStorage thus once a page is closed, it will create a new session when opening a new browser tab.

localStorage doesn't come with a time setting. If a time setting is required then we will need to pair it with a cookie then parse the time and set to localStorage.clear.

Will set a setting when opening a new node to clear storage.

**Comment by jammin84** [comment]
re: time setting. I just thought something like a var that held a timestamp when its updated and checked against later. But you seem to have it under control :smile:

**Comment by MDE186** [comment]
lol...thanks forget about that _hangs head_

**Comment by MDE186** [comment]
Cool thought i was working on branch 5. Do we really need to have the 30second timeout. Will a user stay on the page long enough?

**Comment by jammin84** [comment]
@MDE186 i had said earlier 
"fyi 30sec probably isn't sufficient. They may spend longer than that editing a page. I'm sure you'll come up with something."

**Comment by MDE186** [comment]
@jammin84 So what I've implemented is that each time the node edit page is accessed it clears the sessionstorage thus reverting to tab "node info". The sessionstorage will stay active until the user leaves the page. Ive tested it my side and works fine. but obviously you guys need to test as well.

**Comment by jammin84** [comment]
@MDE186 i haven't tested yet, but I can't see where your saving to sessionStorage only localStorage?

**Comment by MDE186** [comment]
Doh...updated :)

**Comment by jammin84** [comment]
@MDE186 I've tried your revision. 

When i add an ip for example it doesn't go back to the "network" tab.

your test version is here.
http://wafn.jolly.so/wind.dev/wind-mde-patch5/index.php/

**Comment by jammin84** [comment]
oh. there is a typo.

Uncaught ReferenceError: sessionlStorage is not defined

var activeTab = sessionlStorage.getItem('activeTab');

**Comment by MDE186** [comment]
okay cool...must have left the 'l' behind when changing to sessionStorage

**Comment by jammin84** [comment]
Can I also suggest that if there wasn't an activeTab that the info tab is shown as "selected"

```
} else { $('#tabs a[href="#tab-info"]').tab('show'); }
```

**Comment by MDE186** [comment]
Sure no problem..if it works add it :) but it'll always load the info tab as its the first in the list. But yeah it can be defined as default.

**Comment by jammin84** [comment]
@MDE186 i can't modify your branch. So if you can add I'm then happy to merge.

**Comment by MDE186** [comment]
Cool. all updated.

**Comment by jammin84** [comment]
thanks.

**Pull request merged**
