### PR TITLE
Create folders with permissions on first install

### PR DESCRIPTION
**Pull request by MDE186**
Create folders with permissions on first install

### CODE REVIEW

**Comment by jammin84** [comment]
I did some quick testing and realised this isn't going to work due to permissions.

By default the /path/to/www/root/ shouldn't be writable by the www process which the install script is  running as.  So it'll never be able to actually create the folders.

this will need a rethink.

**Comment by spinza** [comment]
Bit of a chicken and egg scenario :)

Why not include the needed folders in the git repo with a small readme or something to make sure it gets included in git.  Then the script can just check the permissions of the folders.

**Comment by jammin84** [comment]
this PR ref #55. I've included some further comments there for now.

**Comment by jammin84** [comment]
FYI. Approved. as it will work if folder perms are correct. otherwise it'll revert to asking for the folders to be fixed.

**Pull request merged**
