### PR TITLE
Update validations of hostnames and node names

### PR DESCRIPTION
**Pull request by spinza**
This checks the first and last character of node names.
Also adds checking for hostnames.

### CODE REVIEW

**Comment by jammin84** [comment]
why limit length to 48chars?

63 is maximum allowed per level.
https://en.wikipedia.org/wiki/Domain_Name_System

Some of our nodes have multiple domains assigned to them. This allows them to match which one they were referring.
Would this check then restrict me from entering hostname.domainname due to length or due to it containing a "."? 
I guess ideally there should be another dropdown next to hostname for the domain portion.

**Comment by spinza** [comment]
**Length**
nodes.name_ns is varchars(50) in the db.  Need an extra 2 for the duplicates.  So if name_ns already exists it adds a -1 or -2 etc to the name.  So 
ip_addresses.hostname is also 50.  Could add 2 for you buy making hostname max 50 and name_ns 48.
**Subdomains**
I can allow a . as a valid char in the text.  Would allow people to do subdomains.  But this would still be a subdomain of name_ns.

So our fqdn for an ip_adddress entry is ip_addresses.hostname + '.' + nodes.name_ns + '.ctwug.za.net' 

I guess you are ignoring name_ns?  So allowing dots will work for you?

**Comment by jammin84** [comment]
thanks for the fqdn, now i understand what your doing.

We use ip_addresses.hostname + '.' + dns_zones.name + '.wafn'

Which allows us a single node to have many domain names.

IE a special "Admin" node has the following domains allocated to it
- anycast.wafn
- games.wafn
- www.wafn

**Comment by spinza** [comment]
**This PR**
I think allowing "." will allow both of us to do what we want for now?

**Bigger discussion again**
I think this is again a bigger discussion.  I think your dns zone setup would be quite complex for us.  We have many many nodes for example.  

To me the best possible model is ip_addresses.hostname + '.' +nodes.name_ns '.' + dns_zones.name.  
But there would be a join between ip_addresses and dns_zones.  I.e. I want to set the ip address for this hostname.name_ns for this zone.

You'd lose duplicate names to some extent, but doesn't seem to be used that often.  Note you could also just edit the name_ns field to the "easy version" of a node name.

Then we could based on your zone data add zone for wafn and zone for say wafn.co.au or so to make your dns available on the web.

Also we "calculate" reverse data based on ip_addresses/nodes data.   Our nodes are too many so we can't give each node a /24 to have a separate reverse zone.   We share a common address space with other wireless networks in South Africa (allowing peering). We "only" get 172.18 and 172.26.

**Comment by spinza** [comment]
Forgot to mention with either model we may need a separate screen to edit the top level dns data. E.g. MX SPF etc.

**Comment by jammin84** [comment]
agreed "." for now.

I'll put further comments in issue #9

**Comment by jammin84** [comment]
err forgot the "." needs doing. If you can add and merge. Then this can be closed.

**Comment by spinza** [comment]
Away for couple of days. Will do when I'm back.

**Pull request merged**
