### PR TITLE
Improve language of change email address verification email

### PR DESCRIPTION
**Pull request by MDE186**
Improve language of change email address verification email

### CODE REVIEW

**Comment by jammin84** [comment]
@MDE186 

```
echo "Could you please use some ".
"line wrapping to keep the code tidy.\n\n".
"Better to implement now than have to tidy later.";
```

**Comment by MDE186** [comment]
Cool. Will go through the whole English file.

**Comment by MDE186** [comment]
Have updated the pull request.

**Comment by jammin84** [comment]
@MDE186 

Neither of your edits (as displayed below) will work as expected.
- The first version is 99% there. it just needs a concat symbol to join the lines by utilising a dot "." between comments (see my example in my previous comment)
- The Second version although coded ok, will lead to massive indent's on emails.

```
 -          'body' => "WiND - Wireless Nodes Database\n"
 -          "------------------------------------------\n"
 -          "Account Activation ##username##\n\n"
 -          "Follow this link to activate your account: ##act_link##"
 +          'body' => "WiND - Wireless Nodes Database\n
 +          ------------------------------------------\n
 +          Account Activation ##username##\n\n
 +          Follow this link to activate your account: ##act_link##"
```

**Comment by MDE186** [comment]
Thanks. All done :)

**Comment by spinza** [comment]
Will test in near future.

**Comment by jammin84** [comment]
line 603 requires a comma at the end of the line before the next array item 'body_suffix'.

The rest looks fine.

**Comment by MDE186** [comment]
Now it should be done :)

**Pull request merged**
