### PR TITLE
DNS zone types. (Fwd n Rev, Forward, Reverse)

### PR DESCRIPTION
**Pull request by jammin84**
This update is a fix for #23. 
This also includes a fix for #11 unable to delete cname

The ip_address record type can now be customised to generate more specfic DNS records:
- Forward only record
- Reverse only record
- A record that does both Forward and Reverse

### CODE REVIEW

**Comment by spinza** [comment]
Ok I'll try and review by next Thursday.

**Comment by jammin84** [comment]
any updates on this one. I'd like to see it gone.

**Comment by spinza** [comment]
Ok will try review tonighy

**Comment by spinza** [comment]
Couple of comments:  
Can the IP comment for forward / reverse records be updated to use include phrase IP address?  Just for some continuity so people here know what is what?
Is there consistency checks for fw/ fw & reverse and reverse?  Should there be?

Anyway otherwise it looks good. 

Do you know what will happen to an upgrade?  Will all existing ip_addresses be upgraded to fw & rev?

**Comment by jammin84** [comment]
Not sure where you mean by "Can the IP comment for forward / reverse records be updated to use include phrase IP address?" 
- if it is a $lang text thing:
  - i tried to keep these as brief as possible.
  - you could use the $lang_overwrite to customise for your site.

consistency checks 
- there isn't any JS ones. 
- In the function output_onpost_form_ipaddr\* it uses your function "validate_hostname()"
- I tested a bad IP -> db will throw "A database error has occured. Please report the problem to the administrator(s)."
  - doesn't look like wind has ever has used the return output of ip2long() to give a more meaningful return message.

db upgrade
- by memory when the column is created all existing records will be set to the column default.
  - the column default is fwdNrev
  - you'll test this right?

**Comment by spinza** [comment]
It's now called "IP Addresses"

I want it to say something "IP Addresses (Forward & Reverse DNS)"
and "IP Addresses (Forward DNS only)"
etc. to provide some continuity in user experience. Our users will get
confused on a new node where to put stuff with just "Forward & Reverse DNS
records".  Plus our user guides reference IP Addresses etc.

Happy with no consistency checks.

In terms of the db upgrade I thought my dev database had ip addresses in
them but after upgrading I could not find any ip addresses to check that
bit. I can redo it.

**Comment by jammin84** [comment]
re field titles -> ip addresses. fair enough. will update

**Comment by jammin84** [comment]
text changes as discussed.

**Comment by jammin84** [comment]
@spinza how goes the testing on this?

**Comment by spinza** [comment]
@jammin84 sorry for the slow work.  I'm overseas for work.  Had some time this evening so checked it out again. 

Almost happy.  Just one thing.  Another cosmetic change.  The Add ... button labels on the right seem inconsistent.  Can they not all say Add IP Address?

image

**Comment by jammin84** [comment]
@spinza yeah they probably could, but i dont plan on changing it as the future plan is for these to be a "+" only button without the text as the heading already describes it ... see issue 62

**Comment by spinza** [comment]
Again user confusion is a problem if I merge this now then?  This will already be confusing for users here so I'm really trying to avoid any unneeded confusion.

**Comment by jammin84** [comment]
How about dropping the words and just leaving it as "+ Add" for all of them ? Seems to work for "Delete"

**Comment by spinza** [comment]
Fine with me yes.  Once you do that I will merge.

**Comment by MDE186** [comment]
Okay so the "+" only has been changed to "+ Add" - this can be done in the language file. Question is are they still moving across to the left instead of the right?

**Comment by jammin84** [comment]
@MDE186 I'll only update the lang file so this pull can be closed out.

I still think the layout on the left would be neater / simpler. But that can be discussed over in that issue between all.

**Comment by spinza** [comment]
Sorry for accidental close.  Merged.

**Comment by jammin84** [comment]
it wont let me add to this pr as it's been merged. So I've created another PR for it.

**Comment by spinza** [comment]
> I'll only update the lang file so this pull can be closed out.

Sorry I thought this meant it would be done in separate PR.  Sorry for merging too soon :)

**Pull request merged**
