### PR TITLE
Update html.tpl

### PR DESCRIPTION
**Pull request by MDE186**
Move literal and add missing /

### CODE REVIEW

**Comment by spinza** [comment]
I have checked-out this pull at https://wind-dev.ctwug.za.net/
Please review and see if you are happy.
It looks as if it's working to me.

**Comment by spinza** [comment]
@jammin84 does this seem ok?  You can test it on our wind-dev if you are pressed for time.

**Comment by spinza** [comment]
Helps with #10

**Comment by spinza** [comment]
@jammin84 can I merge?

**Comment by jammin84** [comment]
sorry, i had mis-read your above comments. looks more functional than previous. good work peeps.

oh, and thanks for letting me know it was up on your dev server ;)

**Comment by spinza** [comment]
:+1:

**Pull request merged**
