### PR TITLE
Create folders during first install

### PR DESCRIPTION
**Pull request by MDE186**
Sorts out first part of #55

### CODE REVIEW

**Comment by MDE186** [comment]
Sorry for some reason it included my pulls from wind. Just ignore those unless you know a way to remove them? 
This is the updated file #59

**Comment by jammin84** [comment]
@MDE186 good work getting started on this.

you can use the recursive feature of mkdir so you dont have to create each dir manually :wink: 
`mkdir($mkDir, 0777);`
to
`mkdir($mkDir, 0777, true);`

**Comment by MDE186** [comment]
Have updated accordingly.

**Comment by MDE186** [comment]
Sorry for the royal mess. If this is merged I'm going to delete my fork and
start fresh :)

**Comment by spinza** [comment]
@MDE186 I can clean this up but the PR / commits will be from me.  You should be able to fix it quite easily especially because you edited one file only.  

Just close this but note your changes.  Make sure your branch is up to date with master (and the same as master).  I.e. you should not have local commits that are not in master.  Then just apply the change you your new branch and create the PR.

**Pull request closed without merging**
