### PR TITLE
Make sure "MAIL FROM" is set correctly to make sure Return-Path is fine

### LINKED ISSUE #13: Sent mail is not getting a proper Return-Path
Should be set properly to make sure mail is not sent to spam on recipients (e.g. GMail and Yahoo).
Seems the correct way to get this working is:

``` php5
$to = "Recipient Name <recipient@externaldomain.com>";
        $subject = "Test Message";
        $message = "This is the body of the email.";
        $from = "Sender Name <sender@mydomain.com>";
        $returnpath = "<bounce@mydomain.com>";
        $headers = "From: $from";
        $additional = "-f$returnpath";
        mail($to, $subject, $message, $headers, $additional);
```

I want to add `$additional='-f<'.$vars['mail']['from'].'>'`  This needs to be a valid mail address for the sending server for SPF purposes.  So can't use the from (as this might be any user email).

And then also change the `return @mail($to, $subject, $body, $headers);` to `return @mail($to, $subject, $body, $headers,$additional);`
See: 
https://github.com/southern-wind/wind/blob/master/globals/functions.php#L370

### PR DESCRIPTION
**Pull request by spinza**
So SPF will work and mail doesn't end up in spam. Fixes #13.

### CODE REVIEW

**Comment by jammin84** [comment]
spinza, this should already be covered @ line 383 in the headers.

$headers = "From: $from\n";

I dont get how this is breaking SPF?

Can you provide example headers of the difference in from output from before and after code change?

**Comment by spinza** [comment]
From is just the from header in the message.  This is independent of the mechanics of sending the email.  
`MAIL FROM` is the address used to send the mail and eventually this sets the `Return-Path`
Below is examples of email headers on this before and after.  Before making change the `Return-Path` gets set to some PHP/sendmail default.  Also note the `Received-SPF: neutral`
After the change the `Return-Path` is not set to the wind email address.  Could also make it somethinge like noreply@example.com in theory.  Note the `Received-SPF: pass`

Before change:

```
Delivered-To: xxx@gmail.com
Received: by 10.194.152.170 with SMTP id uz10csp2480468wjb;
        Tue, 12 Jan 2016 03:14:12 -0800 (PST)
X-Received: by 10.28.64.131 with SMTP id n125mr9629896wma.65.1452597252138;
        Tue, 12 Jan 2016 03:14:12 -0800 (PST)
Return-Path: <www-data@localhost.localdomain>
Received: from mail.ctwug.za.net (matter.ctwug.za.net. [31.187.70.231])
        by mx.google.com with ESMTPS id u8si23396974wje.114.2016.01.12.03.14.12
        for <xxx@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 12 Jan 2016 03:14:12 -0800 (PST)
Received-SPF: neutral (google.com: 31.187.70.231 is neither permitted nor denied by best guess record for domain of www-data@localhost.localdomain) client-ip=31.187.70.231;
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 31.187.70.231 is neither permitted nor denied by best guess record for domain of www-data@localhost.localdomain) smtp.mailfrom=www-data@localhost.localdomain
Received: from localhost (localhost.localdomain [127.0.0.1])
    by mail.ctwug.za.net (Postfix) with ESMTP id D833F3A2003F
    for <xxx@ctwug.za.net>; Tue, 12 Jan 2016 13:14:11 +0200 (SAST)
X-Virus-Scanned: Debian amavisd-new at mail.ctwug.za.net
Received: from mail.ctwug.za.net ([127.0.0.1])
    by localhost (mail.ctwug.za.net [127.0.0.1]) (amavisd-new, port 10024)
    with ESMTP id AOt4P3GzE5gT for <xxx@ctwug.za.net>;
    Tue, 12 Jan 2016 13:14:10 +0200 (SAST)
Received: from localhost.localdomain (unknown [172.18.1.129])
    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
    (Client did not present a certificate)
    by mail.ctwug.za.net (Postfix) with ESMTPS
    for <xxx@ctwug.za.net>; Tue, 12 Jan 2016 13:14:10 +0200 (SAST)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
    by localhost.localdomain (8.14.4/8.14.4/Debian-4.1ubuntu1) with ESMTP id u0CBEAUB000482
    for <xxx@ctwug.za.net>; Tue, 12 Jan 2016 13:14:10 +0200
Received: (from www-data@localhost)
    by localhost.localdomain (8.14.4/8.14.4/Submit) id u0CBEAdX000481;
    Tue, 12 Jan 2016 13:14:10 +0200
Date: Tue, 12 Jan 2016 13:14:10 +0200
Message-Id: <201601121114.u0CBEAdX000481@localhost.localdomain>
To: xxx@ctwug.za.net
Subject: Password recovery: xxx
X-PHP-Originating-Script: 0:functions.php
From: WIND <wind@ctwug.za.net>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

WiND - Wireless Nodes Database
------------------------------------------

Password recovery for the account xxx

Click here: http://wind.ctwug.za.net/?p
```

After change:

```
Delivered-To: xxx@gmail.com
Received: by 10.194.152.170 with SMTP id uz10csp3386973wjb;
        Wed, 13 Jan 2016 12:37:41 -0800 (PST)
X-Received: by 10.194.94.232 with SMTP id df8mr173705wjb.25.1452717461511;
        Wed, 13 Jan 2016 12:37:41 -0800 (PST)
Return-Path: <wind@ctwug.za.net>
Received: from mail.ctwug.za.net (matter.ctwug.za.net. [31.187.70.231])
        by mx.google.com with ESMTPS id bz19si4371158wjb.232.2016.01.13.12.37.39
        for <xxx@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 13 Jan 2016 12:37:39 -0800 (PST)
Received-SPF: pass (google.com: domain of wind@ctwug.za.net designates 31.187.70.231 as permitted sender) client-ip=31.187.70.231;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of wind@ctwug.za.net designates 31.187.70.231 as permitted sender) smtp.mailfrom=wind@ctwug.za.net
Received: from localhost (localhost.localdomain [127.0.0.1])
    by mail.ctwug.za.net (Postfix) with ESMTP id 32B3A3A22AFD
    for <xxx@ctwug.za.net>; Wed, 13 Jan 2016 22:37:37 +0200 (SAST)
X-Virus-Scanned: Debian amavisd-new at mail.ctwug.za.net
Received: from mail.ctwug.za.net ([127.0.0.1])
    by localhost (mail.ctwug.za.net [127.0.0.1]) (amavisd-new, port 10024)
    with ESMTP id SZrgTfzGP44Y for <xxx@ctwug.za.net>;
    Wed, 13 Jan 2016 22:37:35 +0200 (SAST)
Received: from centrifuge.ctwug.za.net (unknown [172.18.1.129])
    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
    (Client did not present a certificate)
    by mail.ctwug.za.net (Postfix) with ESMTPS
    for <xxx@ctwug.za.net>; Wed, 13 Jan 2016 22:37:35 +0200 (SAST)
Received: from centrifuge.ctwug.za.net (localhost.localdomain [127.0.0.1])
    by centrifuge.ctwug.za.net (8.14.4/8.14.4/Debian-4.1ubuntu1) with ESMTP id u0DKbYop026272
    for <xxx@ctwug.za.net>; Wed, 13 Jan 2016 22:37:34 +0200
Received: (from www-data@localhost)
    by centrifuge.ctwug.za.net (8.14.4/8.14.4/Submit) id u0DKbYRs026271;
    Wed, 13 Jan 2016 22:37:34 +0200
Date: Wed, 13 Jan 2016 22:37:34 +0200
Message-Id: <201601132037.u0DKbYRs026271@centrifuge.ctwug.za.net>
X-Authentication-Warning: centrifuge.ctwug.za.net: www-data set sender to <wind@ctwug.za.net> using -f
To: xxx@ctwug.za.net
Subject: Password recovery: xxx
X-PHP-Originating-Script: 0:functions.php
From: WIND <wind@ctwug.za.net>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

WiND - Wireless Nodes Database
------------------------------------------

Password recovery for the account xxx

Click here: http://wind.ctwug.za.net/?p.....
```

Note I have forwading to gmail enabled which complicates things slightly but doesn't change the outcome. xxx@ctwug.za.net is my wind email and xxx@gmail.com is the email it forwards to.

**Comment by jammin84** [comment]
Awesome. ta.

Return-Path: www-data@localhost.localdomain .... hehe. 

The neutral is just because @localhost.localdomain doesn't have an SPF record to check against (see "dig TXT localhost.localdomain"). 

The spam issue is more because the return address is a generic localhost domain and spam filters dont take kindly to these.

I think the better/simple result would be to just add "Return-Path: $from" into the headers rather than utilising the additional field, which is duplicating the headers section and may cause confusion at a later point.

Even the php mail examples shows it as an either or - See example 2 vs example 3. (http://php.net/manual/en/function.mail.php#refsect1-function.mail-examples)

**Comment by spinza** [comment]
It has to be example 3.

You cannot add the Return-Path as a header as it will be removed when sent.  It get's set as part of the MTA transaction and is not a header.
See the top answer on
http://stackoverflow.com/questions/1235534/what-is-the-behavior-difference-between-return-path-reply-to-and-from
for
an explanation.

Also this change has helped with yahoo.com who weren't even delivering our
mail to spam.  It now appears in spam.  Passing SPF it does now reach the
spam folder.

I am also fixing the localhost issues, setting hostnames on my servers
properly.

**Comment by spinza** [comment]
Can I merge this?  It won't break anything.

**Comment by jammin84** [comment]
Should probably use "$from_email" rather than $var.

But other than that looks good.

**Comment by spinza** [comment]
~~~I'll test that.~~~
See below.

**Comment by spinza** [comment]
If you use `$from_email` that would be a problem.  For people contacting a node the from email could be something@gmail.com or whatever address they are using. 
In that case SPF would fail as the wind server is not allowed to send email on behalf of @gmail.com or other domains.

**Comment by jammin84** [comment]
good point, agreed.

**Comment by spinza** [comment]
Thanks :+1:

**Pull request merged**
