### PR TITLE
Verify e-mail address

### PR DESCRIPTION
**Pull request by MDE186**
Verify e-mail address when user is registering

### CODE REVIEW

**Comment by spinza** [comment]
Does this also apply to email address changes?

**Comment by MDE186** [comment]
Yes.

When you register or modify your email address and you for instance add two
@@ it will give the below.

clipboard01

clipboard02

**Comment by spinza** [comment]
Tested this.  When I change to a valid email and press ok I get a "General Error". 
When I then click back and OK again (without changing the email) it works.

The test does stop invalid emails from being accepted though.

**Comment by MDE186** [comment]
Weird because I ran multiple tests and didn't receive any errors. Maybe
stuck cache?

**Comment by spinza** [comment]
I'll try in incognito to rule that out.

**Comment by spinza** [comment]
Nope, changing to a valid email:
image

**Comment by MDE186** [comment]
Okay will look at it...will download chrome and test. I use firefox.

**Comment by spinza** [comment]
wind-dev.ctwug.za.net is currently on your branch so you can test there.

**Comment by MDE186** [comment]
Hey spin,

Did you update the language files as well?

**Comment by MDE186** [comment]
Also is the email activation enabled? Might be an error trying to send out
the activation email?

**Comment by spinza** [comment]
I'll check the email sending bit.  Does it resend the email on an email address change?

**Comment by MDE186** [comment]
I signed up but have yet to receive a mail activation which is the reason I
brought it up.

**Comment by spinza** [comment]
Ah will have a look at that.

**Comment by spinza** [comment]
OK you were right.  The email wasn't set up on wind-dev.  That's what caused the error. I fxied this.  You should be able to re-register.

I test and it's working perfectly for me.  @jammin84 do you want to review as well?

**Comment by spinza** [comment]
This should fix #17

**Comment by spinza** [comment]
@jammin84 going to merge this by end of week unless I hear from you.

**Comment by jammin84** [comment]
Sorry guys, had a broken phone for a while there, so I must have missed my notices for this.

If it's been tested successfully by someone other than the coder, I'm happy for this to be merged.

**Comment by spinza** [comment]
Thanks @MDE186 !

**Comment by MDE186** [comment]
No problem.

**Pull request merged**
