### PR TITLE
Change all ip columns to unsigned int(10).  Fixes #41

### LINKED ISSUE #41: All IP columns in database should be unsigned int(10)
The pre 1.1 sql has a bunch of issues in this regard.

### PR DESCRIPTION
**Pull request by spinza**
Fixes #41

### CODE REVIEW

**Comment by MDE186** [comment]
Hey, I updated my database with your chnages but cannot add ip information under subnet.

I.e. if i enter 172.18.221.1 - 172.18.221.5 > it shows - 0.0.0.0 0.0.0.0

**Comment by jammin84** [comment]
makes sense.

**Comment by spinza** [comment]
Do you want me to reopen this? And change to a schema update?

**Comment by spinza** [comment]
Shall this become 1.2 then ip cname 1.3 and yours 1.4?

**Comment by jammin84** [comment]
Its probably more correct. 

But seeing as 1.2 was already released with ip cname, I'm happy if you ammend 1.2 to include it.

**Comment by spinza** [comment]
Ok 1.2 is this plus ip cname and then yours

**Comment by jammin84** [comment]
:+1:

**Pull request merged**
