### PR TITLE
Add node level CNAME editing and the mysql table to store the data

### PR DESCRIPTION
**Pull request by spinza**
First draft of this.  Working on my side.  Added the schema changes as well.  Pushes schema to v1.2.
Let me know what you think.

This does not add the actual dns functionality.

### CODE REVIEW

**Comment by jammin84** [comment]
I dont think CNAME should be its own table. We should also be able to record SRV, MX, TXT, etc fields to properly populate the generation of dns records

I think the right way forward would be the exisiting table "ip_addresses" should be restructured.

Currently its:
id, date_in, hostname, ip, mac, node_id, type,always_on, info, zone_type

zone_type is "forward" or "reverse"

I think mac, type, always_on and info are unnecessary fields:
Type = "router", "wireless bridge", "server", etc
always_on = Y / N
info = text description field.
mac = why is this needed? Is there some DHCP pulling this info?
@spinza have you seen any useful input/output from this? It's really just duplicating the "Services" tab

Fields to add:
Content, Type, TTL
Content = textual data for record
Type = PTR, MX, TXT, etc (I'll call this rType so as not to confuse with the exisiting Type field)
TTL = default 3600

Examples

| id | date_in | hostname | ip | content | ttl | node_id | r_type | zone_type |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | now() | test.domain |  | test2.domain | 3600 | 1 | CNAME | forward |
| 2 | now() | test.domain |  | PUSSYCATS | 3600 | 1 | TXT | forward |
| 3 | now() | test.domain |  | test3.domain | 3600 | 1 | MX | forward |
| 4 | now() | test2.domain | 192.168.1.1 |  | 3600 | 1 | PTR | forward |
| 5 | now() | test2.domain | 192.168.1.1 |  | 3600 | 1 | PTR | reverse |
| 6 | now() | test3.domain | 192.168.1.2 |  | 3600 | 1 | PTR | forward |
| 6 | now() | mx.test.domain | 192.168.1.2 |  | 3600 | 1 | PTR | reverse |

**Comment by spinza** [comment]
I broadly agree with you. 

My main problem is that we already use cname in the way I've set it out above.  So I really would have to use it like that (for now).  My time pressure is that Wind is running on a server that needs to be switched off soon.  I'm building the replacement and need it up in a couple of weeks.  I also need to move forums, wiki etc off the same server.  I'm doing the right thing and splitting things up to singe use server.  Currently everything is mangled together on one server :(

So my focus is getting functionality working as is.  The open PRs here would do that for me.  I could run a separate version live I guess.

I do think we need to think about how we are going to make things better going forward.  And prioritise etc.  Many ideas here as you've covered.
- Other DNS records. 
- Separate(?) recording details of devices (MAC / always on etc) and IPs.  The current setup seems mixed up.  Especially given that the same device could have multiple IPs.
- Tracking modified timestamp for each record allowing us to set `zone serial = select max(unix_timestamp(modified)`.  I've essentially done this on our setup already.
- Root level dns entries (e.g. mail.ctwug.za.net, www.ctwug.za.net, MX, SPF, TXt, CNAMEs) etc. 
- What we do with integration with actual DNS provision.  Mine is going to powerdns (currently bind with customised mysql driver).  We could make this part of wind (mainly the dns entries) or we could leave it to the user to implement.  Or make it tightly linked to powerdns only.
- There is also the problem of user education.  If I suddenly expose users to full spectrum of dns entries on our side someone will regularly break dns on our side.  We just have too many clueless people entering things ( I partially include myself here).  So we need some serious validation on user input.
- Allowing people to set their wug side and internet side ips on their dns records (or private and public domain is ctwug.za.net so we can have both).  Given that we have internet side dns.  I was thinking of allowing guys to for their node set the internet side ip/dns records.  E.g. www.mynode.ctwug.za.net has the private wug ip on one side and a (dynamic) ip on the internet side.  Basically giving them dyndns service.
- We need to look at powerdns mysql data formats (I will be doing this shortly so can provide feedback).  This will be good table structure to consider as this will cover DNS use cases clearly.  And will make integration easier. 
- DNS multimaster sync. I have this set up but we could in theory integrate some of this.
  We could start raising issues for the above and plan this?

Can I ask that I be allowed to add CNAME now and then we "sit down" and plan where we are headed?  Happy to remove it later once we have a plan.  If not I'll run the branch and rebase.

**Comment by jammin84** [comment]
"Can I ask that I be allowed to add CNAME now and then we "sit down" and plan where we are headed?"
agreed, move the core ideas to a separate issue to be resolved at a future date.

**Comment by spinza** [comment]
Merged as discussed.

**Pull request merged**
