### PR TITLE
fix frequency and link type selection defaults

### PR DESCRIPTION
**Pull request by jammin84**
fix frequency selection default for #40.

Picks the default from the table in the database when no previous value has been entered.

### CODE REVIEW

**Comment by spinza** [comment]
If I open a new link the default remains 2400 ish:
selection_001

**Comment by jammin84** [comment]
It picks the database default for that field ... Mine was already 5400 .... I don't recall modifying it in testing .... Did you do this on a fresh db import?

**Comment by jammin84** [comment]
Schema.sql > links table shows frequency default is 5500.

So it should be that.

**Comment by spinza** [comment]
Will look again

**Comment by spinza** [comment]
Sorry I'm gonna test this and then the fw&rev.

**Comment by spinza** [comment]
Just tested again.  Go to existing node.  Click add link then I get this:
image
Note the frequency.

I checked the database and the default is correct there:
image

You can try it out yourself on https://wind-dev.ctwug.za.net

**Comment by jammin84** [comment]
K. I'll check it again later.

**Comment by jammin84** [comment]
think i'd manually github done this update. looks like I'd pasted the fix into the wrong section.

Anyways, this now fixes frequency and the link type selection boxes :wink:

**Comment by spinza** [comment]
Wil review this also.

**Comment by spinza** [comment]
That's better.

**Pull request merged**
