### PR TITLE
Rework how database updates are structured and fix issues in schema 1.1 and schema 1.2

### PR DESCRIPTION
**Pull request by spinza**
This rewords the update structure per comments in #49 .  Note this does not fix the schema changes.

### CODE REVIEW

**Comment by jammin84** [comment]
Haven't tested. But looks great.

Can you just add some comments on the code for
tools/update.php for future code readers.

**Comment by spinza** [comment]
Will do.
This also fixes the schema changes.  I had thought to do two PRs but it was just a lot easier in one.

**Comment by spinza** [comment]
Done the comments.  Will create issue for other changes suggested.

**Comment by jammin84** [comment]
tools/update.php
Line 3 and 11 use incorrect block code comment notation `//*`should be single `/*`

Otherwise, looks good.

### Fresh install of 1.2 version

success.

### Upgrade from 1.1 version.

```
# php update.php
Connected to server "localhost@wind.dev" on database "wind-fullfixschema12".
Schema is currently at v1.1 version
Upgrading DB Schema to v1.2...
```

**Comment by spinza** [comment]
Sorry the comments highlighted in my editor so I thought they were fine.

**Comment by spinza** [comment]
Did your upgrade work?

**Comment by jammin84** [comment]
After I edited the comment thing. Yes it appeared to work.

Checked the tables and it looked like everything applied correctly.
Update_log also showed 1.2

**Comment by jammin84** [comment]
Oh. I see why you asked. The log from the update script never says complete or success.

Perhaps add that as an output post upgrade?

**Comment by spinza** [comment]
Done?

**Comment by jammin84** [comment]
Good work on this one @spinza

**Comment by spinza** [comment]
Thanks :smile:

**Pull request merged**
